
User.create!(
  [
    {email: 'test1@test.com',name: 'テスト太郎',password: 'test0000',active_image: 1},
    {email: 'test2@test.com',name: 'テスト2郎',password: 'test0000',active_image: 2},
    {email: 'test3@test.com',name: 'テスト3郎',password: 'test0000',active_image: 3},
    {email: 'test4@test.com',name: 'テスト4郎',password: 'test0000',active_image: 1},
    {email: 'test5@test.com',name: 'テスト5郎',password: 'test0000',active_image: 2},
    {email: 'test6@test.com',name: 'テスト6郎',password: 'test0000',active_image: 3},
    {email: 'test7@test.com',name: 'テスト7郎',password: 'test0000',active_image: 1},
    {email: 'test8@test.com',name: 'テスト8郎',password: 'test0000',active_image: 2},
    {email: 'test9@test.com',name: 'テスト9郎',password: 'test0000',active_image: 3},
    {email: 'test10@test.com',name: 'テスト10郎',password: 'test0000',active_image: 1},
  ]
)

# Result.create!(
#   [
#     {user_id: 1, score:100, total_type:10, speed: 1},
#     {user_id: 2, score:200, total_type:100, speed:1},
#     {user_id: 3, score:300, total_type:10, speed: 1},
#     {user_id: 4, score:400, total_type:100, speed:1},
#     {user_id: 5, score:500, total_type:10, speed: 1},
#     {user_id: 6, score:600, total_type:100, speed:1},
#     {user_id: 7, score:700, total_type:10, speed: 1},
#     {user_id: 8, score:800, total_type:100, speed:1},
#     {user_id: 9, score:900, total_type:10, speed: 1},
#     {user_id: 10, score:1000, total_type:100, speed:1},
#   ]
# )

Keyword.create!(
  [
    #イージーキーワード（６文字以下）
    {type_text: "wakasa", display_text:"若狭"},
    {type_text: "mikawa", display_text:"三河"},
    {type_text: "tango", display_text:"丹後"},
    {type_text: "yamato", display_text:"大和"},
    {type_text: "uma", display_text:"馬"},
    {type_text: "buzen", display_text:"豊前"},
    {type_text: "susi", display_text:"寿司"},
    {type_text: "iga", display_text:"伊賀"},
    {type_text: "mutu", display_text:"陸奥"},
    {type_text: "kai", display_text:"甲斐"},
    {type_text: "izumo", display_text:"出雲"},
    {type_text: "kouga", display_text:"甲賀"},
    {type_text: "suruga", display_text:"駿河"},
    {type_text: "edo", display_text:"江戸"},
    {type_text: "owari", display_text:"尾張"},
    {type_text: "musasi", display_text:"武蔵"},
    {type_text: "oiran", display_text:"花魁"},
    {type_text: "tusima", display_text:"津島"},
    {type_text: "huji", display_text:"富士"},
    {type_text: "sinogi", display_text:"鎬"},
    {type_text: "oooku", display_text:"大奥"},
    {type_text: "yoriki", display_text:"与力"},
    {type_text: "dousin", display_text:"同心"},
    {type_text: "detti", display_text:"丁稚"},
    {type_text: "hikesi", display_text:"火消し"},
    {type_text: "sirasu", display_text:"白洲"},
    {type_text: "koban", display_text:"小判"},
    {type_text: "katuo", display_text:"鰹"},
    {type_text: "tyaya", display_text:"茶屋"},
    {type_text: "kasi", display_text:"河岸"},
    {type_text: "hikyaku", display_text:"飛脚"},
    {type_text: "nengu", display_text:"年貢"},
    {type_text: "sinobi", display_text:"忍"},
    {type_text: "daiku", display_text:"大工"},
    {type_text: "tegata", display_text:"手形"},
    {type_text: "kusi", display_text:"櫛"},
    {type_text: "haori", display_text:"羽織"},
    {type_text: "inrou", display_text:"印籠"},
    {type_text: "mage", display_text:"髷"},
    {type_text: "ohaguro", display_text:"お歯黒"},
    {type_text: "sekisyo", display_text:"関所"},
    {type_text: "yasi", display_text:"香具師"},
    {type_text: "tozama", display_text:"外様"},
    {type_text: "hudai", display_text:"譜代"},
    {type_text: "kabuki", display_text:"歌舞伎"},
    {type_text: "husin", display_text:"普請"},
    {type_text: "geisya", display_text:"芸者"},
    {type_text: "dejima", display_text:"出島"},
    {type_text: "kuge", display_text:"公家"},
    {type_text: "hanabi", display_text:"花火"},
    {type_text: "yotaka", display_text:"夜鷹"},
    {type_text: "sumou", display_text:"相撲"},
    {type_text: "syaraku", display_text:"写楽"},
    #ノーマルキーワード（7文字以上１０文字以下）
    {type_text: "tenpura", display_text:"天ぷら"},
    {type_text: "senryoubako", display_text:"千両箱"},
    {type_text: "sukimono", display_text:"数寄者"},
    {type_text: "bateren", display_text:"伴天連"},
    {type_text: "kurohune", display_text:"黒船"},
    {type_text: "gokenin", display_text:"御家人"},
    {type_text: "katanagari", display_text:"刀狩"},
    {type_text: "seppuku", display_text:"切腹"},
    {type_text: "rokumonsen", display_text:"六文銭"},
    {type_text: "sasimonosi", display_text:"指物師"},
    {type_text: "kyoukaku", display_text:"侠客"},
    {type_text: "oniwaban", display_text:"御庭番"},
    {type_text: "ootorimono", display_text:"大捕物"},
    {type_text: "daimyou", display_text:"大名"},
    {type_text: "meakasi", display_text:"目明かし"},
    {type_text: "matibugyou", display_text:"町奉行"},
    {type_text: "tootoumi", display_text:"遠江"},
    {type_text: "senryouyakusya", display_text:"千両役者"},
    {type_text: "katimetuke", display_text:"徒士目付"},
    {type_text: "sobakiri", display_text:"蕎麦切り"},
    {type_text: "hattyoudouhu", display_text:"八丁豆腐"},
    {type_text: "oometuke", display_text:"大目付"},
    {type_text: "yosiwara", display_text:"yosiwara"},
    {type_text: "umamawariyaku", display_text:"馬廻役"},
    {type_text: "soubujirei", display_text:"惣無事令"},
    {type_text: "kirisitan", display_text:"キリシタン"},
    {type_text: "kasuteira", display_text:"かすていら"},
    {type_text: "erekiteru", display_text:"エレキテル"},
    {type_text: "botehuri", display_text:"棒手振り"},
    {type_text: "okappiki", display_text:"岡っ引き"},
    {type_text: "matibugyou", display_text:"町奉行"},
    {type_text: "hikesigumi", display_text:"火消組"},
    {type_text: "etigoya", display_text:"越後屋"},
    {type_text: "rangaku", display_text:"蘭学"},
    {type_text: "ukiyoe", display_text:"浮世絵"},
    {type_text: "okabasyo", display_text:"岡場所"},
    {type_text: "settin", display_text:"雪隠"},
    {type_text: "syunga", display_text:"春画"},
    {type_text: "biidoro", display_text:"びいどろ"},
    {type_text: "oteuti", display_text:"お手打ち"},
    {type_text: "busidou", display_text:"武士道"},
    {type_text: "isemairi", display_text:"伊勢参り"},
    {type_text: "terakoya", display_text:"寺子屋"},
    {type_text: "simanagasi", display_text:"島流し"},
    {type_text: "kawaraban", display_text:"瓦版"},
    {type_text: "hatamoto", display_text:"旗本"},
    {type_text: "samurai", display_text:"侍"},
    {type_text: "akazonae", display_text:"赤備"},
    {type_text: "akourousi", display_text:"赤穂浪士"},
    {type_text: "meyasubako", display_text:"目安箱"},
    {type_text: "daimyougyouretu", display_text:"大名行列"},
    {type_text: "sinoukousyou", display_text:"士農工商"},
    #ハードキーワード（11文字以上）
    {type_text: "hiyokomanjuu", display_text:"ひよこ饅頭"},
    {type_text: "hyakusyouikki", display_text:"百姓一揆"},
    {type_text: "toukaidougojuusantugi", display_text:"東海道五十三次"},
    {type_text: "takedakibagundan", display_text:"武田騎馬軍団"},
    {type_text: "ningyoujoururi", display_text:"人形浄瑠璃"},
    {type_text: "kirisutegomen", display_text:"斬捨御免"},
    {type_text: "syouheizakagakumonjo", display_text:"小平坂学問所"},
    {type_text: "sippoutunagi", display_text:"七宝つなぎ"},
    {type_text: "syouruiawareminorei", display_text:"小類憐みの令"},
    {type_text: "dentyuunigozaru", display_text:"殿中にござる"},
    {type_text: "bugeihyappan", display_text:"武芸百般"},
    {type_text: "anseinotaigoku", display_text:"安政の大獄"},
    {type_text: "katusikahokusai", display_text:"葛飾北斎"},
    {type_text: "yorikinoasaburo", display_text:"与力の朝風呂"},
    {type_text: "bizenosahunekanemitu", display_text:"備前長船兼光"},
    {type_text: "ohikeenasutte", display_text:"おひけえなすって"},
    {type_text: "toukaidoutyuuhizakurige", display_text:"東海道中膝栗毛"},
    {type_text: "sankinkoutai", display_text:"参勤交代"},
    {type_text: "bukesyohatto", display_text:"武家諸法度"},
    {type_text: "tokugawadaigongen", display_text:"徳川大権現"},
    {type_text: "hugakusanjuurokkei", display_text:"富岳三十六景"},
    {type_text: "kondeneinensizaihou", display_text:"墾田永年私財法"},
    {type_text: "irohanihoheto", display_text:"いろはにほへと"},
    {type_text: "amakusasiroutokisada", display_text:"天草四郎時貞"},
    {type_text: "yoigosinozenihamotanu", display_text:"宵越しの銭は持たぬ"},
    {type_text: "soituhaikidanee", display_text:"そいつは粋だねえ"},
    {type_text: "teyandeeberaboume", display_text:"てやんでえべらぼうめ"},
    {type_text: "isikawagoemon", display_text:"石川五右衛門"},
    {type_text: "kajitokenkahaedonohana", display_text:"家事と喧嘩は江戸の花"},
    {type_text: "rokuharatandai", display_text:"六波羅探題"},
    {type_text: "sityuuhikimawasi", display_text:"市中引き回し"},
    {type_text: "hatimanbosatu", display_text:"八幡菩薩"},
  ]
)

Item.create!(
  [
    {name: "御館様" , price: 200,image_name: "tonosama"},
    {name: "若様" , price: 300	,image_name:"wakasama"},
    {name: "奥之方", price: 300, image_name:	"hime"},
    {name: "煙玉", price: 100	,image_name:"kemuridama"},
    {name: "同田貫" , price: 100, image_name:	"katana"},
    {name: "種子島" , price: 100, image_name:	"tanegasima"},
    {name: "十文字", price: 100, image_name:	"yari"},
    {name: "百姓道具", price: 100, image_name: "kuwa"},
    {name: "石畚", price: 100, image_name: "isi"},
    {name: "大忍", price: 100, image_name: "ninja"},
    {name: "くノ一", price: 100, image_name: "kunoiti"},
    {name: "百姓", price: 100, image_name: "noumin"},
    {name: "辻斬", price: 100, image_name: "tujigiri"},
    {name: "陰陽師", price: 100, image_name: "onmyouji"},
    {name: "学者", price: 100, image_name: "gakusya"},
    {name: "野伏", price: 100, image_name: "samurai"},
    {name: "門徒衆", price: 100, image_name: "montosyu"},
    {name: "呉服屋", price: 100, image_name: "syonin"},
    {name: "武者", price: 100, image_name: "musya"},
    {name: "僧兵", price: 100, image_name: "benkei"},
    {name: "郡代", price: 100, image_name: "busyou"},
    {name: "先代", price: 100, image_name: "mouri"},
    {name: "足軽", price: 100, image_name: "asigaru"},
    {name: "公方", price: 100, image_name: "hideyosi"},
  ]
)
